# Generated by Django 3.1.5 on 2022-09-20 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='is_active',
            new_name='is_approved',
        ),
    ]
